### ISSUE TITLE
Runs fail on GCP with a KeyError from pandas

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT-kghub-scheduler#14]
NEAT runs (specifically, for KG-PHENIO) start as expected but fail like this:
```
16:00:32  Traceback (most recent call last):
16:00:32    File "/home/jenkinsuser/anaconda3/bin/neat", line 8, in <module>
16:00:32      sys.exit(cli())
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
16:00:32      return self.main(*args, **kwargs)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
16:00:32      rv = self.invoke(ctx)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
16:00:32      return _process_result(sub_ctx.command.invoke(sub_ctx))
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
16:00:32      return ctx.invoke(self.callback, **ctx.params)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
16:00:32      return callback(*args, **kwargs)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/cli.py", line 91, in run
16:00:32      edge_method=yhelp.get_edge_embedding_method(classifier),
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/link_prediction/model.py", line 111, in make_train_valid_data
16:00:32      negative_graph=graphs["neg_training"],
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/embiggen/transformers/link_prediction_transformer.py", line 90, in transform
16:00:32      negative_edge_embedding = self._transformer.transform(negative_graph)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/embiggen/transformers/graph_transformer.py", line 103, in transform
16:00:32      return self._transformer.transform(sources, destinations)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/embiggen/transformers/edge_transformer.py", line 123, in transform
16:00:32      self._transformer.transform(sources),
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/embiggen/transformers/node_transformer.py", line 106, in transform
16:00:32      return self._embedding.loc[nodes].to_numpy()
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
16:00:32      return self._getitem_axis(maybe_callable, axis=axis)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
16:00:32      return self._getitem_iterable(key, axis=axis)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
16:00:32      keyarr, indexer = self._get_listlike_indexer(key, axis)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
16:00:32      self._validate_read_indexer(keyarr, indexer, axis)
16:00:32    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
16:00:32      raise KeyError(f"None of [{key}] are in the [{axis_name}]")
16:00:32  KeyError: "None of [Index(['OBO:FBbt_00004566-biolink:subclass_of-OBO:FBbt_00002984'], dtype='object', name=0)] are in the [index]"
16:00:33  Connection to 35.223.148.190 closed.
```

The issue seems to begin when specifying the negative graph, as per `neat/link_prediction/model.py", line 111, in make_train_valid_data`
But I think the real clue is `OBO:FBbt_00004566-biolink:subclass_of-OBO:FBbt_00002984` - this should be in the graph edgefile.

**Comment by caufieldjh** [comment]
Closing this to focus on issue in kg-phenio repo
