### ISSUE TITLE
ValueError in parsing neat.yaml

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT-kghub-scheduler#4]
This may be more of a NEAT issue, but I've only noticed it so far when running on GCP compute:
```
11:53:57  ../neat-02-09-2022-17-30-12.yaml
11:54:19  Traceback (most recent call last):
11:54:19    File "/home/jenkinsuser/.local/bin/neat", line 8, in <module>
11:54:19      sys.exit(cli())
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
11:54:19      return self.main(*args, **kwargs)
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
11:54:19      rv = self.invoke(ctx)
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
11:54:19      return _process_result(sub_ctx.command.invoke(sub_ctx))
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
11:54:19      return ctx.invoke(self.callback, **ctx.params)
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
11:54:19      return __callback(*args, **kwargs)
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/neat/cli.py", line 50, in run
11:54:19      make_node_embeddings(**node_embedding_args)
11:54:19    File "/home/jenkinsuser/.local/lib/python3.8/site-packages/neat/graph_embedding/graph_embedding.py", line 47, in make_node_embeddings
11:54:19      graph: Graph = Graph.from_csv(**main_graph_args)
11:54:19  ValueError: There might have been an I/O error or the line could contains bytes that are not valid UTF-8
```

for reference, this is what the config file looks like:
```
name: test
description: test
output_directory: test_output
graph_data:
  graph:
    node_path: https://github.com/Knowledge-Graph-Hub/NEAT/blob/main/tests/resources/test_graphs/nodes.tsv
    edge_path: https://github.com/Knowledge-Graph-Hub/NEAT/blob/main/tests/resources/test_graphs/edges.tsv
    verbose: True
    directed: False
    nodes_column: id
    node_types_column: category
    default_node_type: biolink:NamedThing
    sources_column: subject
    destinations_column: object
    default_edge_type: biolink:related_to

upload:
  s3_bucket: kg-hub-public-data
  s3_bucket_dir: test/
  extra_args:
    'ACL': 'public-read'
```

**Comment by caufieldjh** [comment]
Solved...
