### ISSUE TITLE
All NEAT runs will fail if one run encounters a NEAT pre_run_check error

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT-kghub-scheduler#8]
During the Jenkins run, one NEAT run may fail its pre-run checks (e.g., the output directory already exists).
This currently looks like:
```
14:30:11  /home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/pre_run_checks/pre_run_checks.py:71: UserWarning: There are already objects in remote s3 directory: test/scheduler-test-output/
14:30:11    f"There are already objects in remote s3 directory: "
14:30:11  Traceback (most recent call last):
14:30:11    File "/home/jenkinsuser/anaconda3/bin/neat", line 8, in <module>
14:30:11      sys.exit(cli())
14:30:11    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
14:30:11      return self.main(*args, **kwargs)
14:30:11    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
14:30:11      rv = self.invoke(ctx)
14:30:11    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
14:30:11      return _process_result(sub_ctx.command.invoke(sub_ctx))
14:30:11    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
14:30:11      return ctx.invoke(self.callback, **ctx.params)
14:30:11    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
14:30:11      return callback(*args, **kwargs)
14:30:11    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/cli.py", line 45, in run
14:30:11      raise RuntimeError("Failed pre_run_check")
14:30:11  RuntimeError: Failed pre_run_check
```
This is fine for one NEAT run but it's entirely possible that other NEAT configs are completely valid.
The RuntimeError causes the Jenkins run to consider itself failed.
We can isolate the error and provide an aggregate output of which attempted NEAT runs failed vs. succeeded.

**Comment by justaddcoffee** [comment]
> The RuntimeError causes the Jenkins run to consider itself failed.

Is this considered failed because of the return value of `run_neat.sh`? If so, we can follow [this](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/523e6d909f9017fc2e319ff2a9727400b0e21810/Jenkinsfile#L74) pattern to catch whether the return value was 0, but not make the pipeline fail

```
def run_py_dl = sh(
    script: '. venv/bin/activate && python3.8 run.py download', returnStatus: true
)
if (run_py_dl == 0) {
    if (env.BRANCH_NAME != 'master') { // upload raw to s3 if we're on correct branch
        echo "Will not push if not on correct branch."
    }
}
```

**Comment by caufieldjh** [comment]
This is resolved - think it just got taken care of in a different branch than the one linked here
